// examples/vue/store-context/src/App.vue
<script setup lang="ts">
import { defineComponent, h, inject, provide } from 'vue'
import {
  createAtom,
  Store,
  useAtom,
  useSelector,
  useValue,
} from '@tanstack/vue-store'
import type { Atom } from '@tanstack/vue-store'
import type { InjectionKey } from 'vue'

// one drawback of storing stores and atoms in context is you have to define types for the context manually, instead of everything being inferred.

type CounterStore = {
  cats: number
  dogs: number
}

type StoreContextValue = {
  votesStore: Store<CounterStore>
  countAtom: Atom<number>
}

const StoreContextKey = Symbol(
  'StoreContext',
) as InjectionKey<StoreContextValue>

function useStoreContext() {
  const value = inject(StoreContextKey)

  if (!value) {
    throw new Error('Missing StoreProvider for StoreContext')
  }

  return value
}

// Vue setup runs once per component instance, so stores and atoms created here stay stable for this provider instance.
const votesStore = new Store<CounterStore>({
  cats: 0,
  dogs: 0,
})
const countAtom = createAtom(0)

provide(StoreContextKey, { votesStore, countAtom })

const CatCard = defineComponent(() => {
  const { votesStore } = useStoreContext()
  // select a value from the store with useSelector
  const value = useSelector(votesStore, (state) => state.cats)

  return () => h('p', `Cats: ${value.value}`)
})

const DogCard = defineComponent(() => {
  const { votesStore } = useStoreContext()
  // select a value from the store with useSelector
  const value = useSelector(votesStore, (state) => state.dogs)

  return () => h('p', `Dogs: ${value.value}`)
})

const TotalCard = defineComponent(() => {
  const { votesStore } = useStoreContext()
  // custom selector to calculate total votes from the store state
  const total = useSelector(votesStore, (state) => state.cats + state.dogs)

  return () => h('p', `Total votes: ${total.value}`)
})

const AtomSummary = defineComponent(() => {
  const { countAtom } = useStoreContext()
  const count = useValue(countAtom)

  return () => h('p', `Atom count: ${count.value}`)
})

const NestedAtomControls = defineComponent(() => {
  const { countAtom } = useStoreContext()

  return () =>
    h('div', [
      h(
        'button',
        {
          type: 'button',
          onClick: () => countAtom.set((prev: number) => prev + 1),
        },
        'Increment atom',
      ),
      h(
        'button',
        { type: 'button', onClick: () => countAtom.set(0) },
        'Reset atom',
      ),
    ])
})

const DeepAtomEditor = defineComponent(() => {
  const { countAtom } = useStoreContext()
  const [count, setCount] = useAtom(countAtom)

  return () =>
    h('div', [
      h('p', `Editable atom count: ${count.value}`),
      h(
        'button',
        { type: 'button', onClick: () => setCount((prev: number) => prev + 5) },
        'Add 5 to atom',
      ),
    ])
})

const StoreButtons = defineComponent(() => {
  const { votesStore } = useStoreContext()

  return () =>
    h('div', [
      h(
        'button',
        {
          type: 'button',
          onClick: () =>
            votesStore.setState((prev: CounterStore) => ({
              ...prev,
              cats: prev.cats + 1,
            })),
        },
        'Add cat',
      ),
      h(
        'button',
        {
          type: 'button',
          onClick: () =>
            votesStore.setState((prev: CounterStore) => ({
              ...prev,
              dogs: prev.dogs + 1,
            })),
        },
        'Add dog',
      ),
    ])
})
</script>

<template>
  <main>
    <h1>Vue Store Context</h1>
    <p>
      This example provides both atoms and stores through a single typed context
      object, then consumes them from nested components.
    </p>
    <CatCard />
    <DogCard />
    <TotalCard />
    <StoreButtons />
    <section>
      <h2>Nested Atom Components</h2>
      <AtomSummary />
      <NestedAtomControls />
      <DeepAtomEditor />
    </section>
  </main>
</template>

// examples/angular/store-context/src/app/app.component.ts
import { Component, InjectionToken, inject } from '@angular/core'
import {
  createAtom,
  injectAtom,
  injectSelector,
  injectSetValue,
  injectValue,
  Store,
} from '@tanstack/angular-store'
import type { Atom } from '@tanstack/angular-store'

// one drawback of storing stores and atoms in context is you have to define types for the context manually, instead of everything being inferred.

type CounterStore = {
  cats: number
  dogs: number
}

const VOTES_STORE = new InjectionToken<Store<CounterStore>>('votes-store')
const COUNT_ATOM = new InjectionToken<Atom<number>>('count-atom')

@Component({
  selector: 'app-root',
  standalone: true,
  providers: [
    {
      provide: VOTES_STORE,
      useFactory: () =>
        new Store<CounterStore>({
          cats: 0,
          dogs: 0,
        }),
    },
    {
      provide: COUNT_ATOM,
      useFactory: () => createAtom(0),
    },
  ],
  template: `
    <main>
      <h1>Angular Store Context</h1>
      <p>
        This example provides both atoms and stores through Angular DI, then
        consumes them from the same component tree with TanStack Store hooks.
      </p>
      <p>Cats: {{ cats() }}</p>
      <p>Dogs: {{ dogs() }}</p>
      <p>Total votes: {{ total() }}</p>
      <div>
        <button type="button" (click)="addCat()">Add cat</button>
        <button type="button" (click)="addDog()">Add dog</button>
      </div>
      <section>
        <h2>Nested Atom Components</h2>
        <p>Atom count: {{ count() }}</p>
        <div>
          <button type="button" (click)="setCount((prev) => prev + 1)">
            Increment atom
          </button>
          <button type="button" (click)="setCount(0)">Reset atom</button>
        </div>
        <div>
          <p>Editable atom count: {{ editableCount() }}</p>
          <button type="button" (click)="setEditableCount((prev) => prev + 5)">
            Add 5 to atom
          </button>
        </div>
      </section>
    </main>
  `,
})
export class AppComponent {
  votesStore = inject(VOTES_STORE)
  countAtom = inject(COUNT_ATOM)
  private readonly editableAtom = injectAtom(this.countAtom)

  cats = injectSelector(this.votesStore, (state) => state.cats)
  dogs = injectSelector(this.votesStore, (state) => state.dogs)
  total = injectSelector(this.votesStore, (state) => state.cats + state.dogs)
  count = injectValue(this.countAtom)
  setCount = injectSetValue(this.countAtom)
  editableCount = this.editableAtom[0]
  setEditableCount = this.editableAtom[1]

  addCat() {
    this.votesStore.setState((prev) => ({
      ...prev,
      cats: prev.cats + 1,
    }))
  }

  addDog() {
    this.votesStore.setState((prev) => ({
      ...prev,
      dogs: prev.dogs + 1,
    }))
  }
}
