// packages/react-store/src/useStore.ts
'use client'

import { useSelector } from './useSelector'

/**
 * Deprecated alias for {@link useSelector}.
 *
 * @example
 * ```tsx
 * const count = useStore(counterStore, (state) => state.count)
 * ```
 *
 * @deprecated Use `useSelector` instead.
 */
export const useStore = <TSource, TSelected = NoInfer<TSource>>(
  source: {
    get: () => TSource
    subscribe: (listener: (value: TSource) => void) => {
      unsubscribe: () => void
    }
  },
  selector: (snapshot: TSource) => TSelected = (s) => s as unknown as TSelected,
  compare?: (a: TSelected, b: TSelected) => boolean,
) => useSelector(source, selector, { compare })

// packages/solid-store/src/useStore.ts
import { useSelector } from './useSelector'
import type { Accessor } from 'solid-js'

/**
 * Deprecated alias for {@link useSelector}.
 *
 * @example
 * ```tsx
 * const count = useStore(counterStore, (state) => state.count)
 * ```
 *
 * @deprecated Use `useSelector` instead.
 */
export const useStore = <TSource, TSelected = NoInfer<TSource>>(
  source: {
    get: () => TSource
    subscribe: (listener: (value: TSource) => void) => {
      unsubscribe: () => void
    }
  },
  selector: (snapshot: TSource) => TSelected = (value) =>
    value as unknown as TSelected,
  compare?: (a: TSelected, b: TSelected) => boolean,
): Accessor<TSelected> => useSelector(source, selector, { compare })
