// packages/solid-store/src/index.tsx
import { createSignal, onCleanup } from 'solid-js'
import type { Derived, Store } from '@tanstack/store'
import type { Accessor } from 'solid-js'

export * from '@tanstack/store'

/**
 * @private
 */
export type NoInfer<T> = [T][T extends any ? 0 : never]

export function useStore<TState, TSelected = NoInfer<TState>>(
  store: Store<TState, any>,
  selector?: (state: NoInfer<TState>) => TSelected,
): Accessor<TSelected>
export function useStore<TState, TSelected = NoInfer<TState>>(
  store: Derived<TState, any>,
  selector?: (state: NoInfer<TState>) => TSelected,
): Accessor<TSelected>
export function useStore<TState, TSelected = NoInfer<TState>>(
  store: Store<TState, any> | Derived<TState, any>,
  selector: (state: NoInfer<TState>) => TSelected = (d) => d as any,
): Accessor<TSelected> {
  const [signal, setSignal] = createSignal(selector(store.state))

  const unsub = store.subscribe(() => {
    const data = selector(store.state)
    if (shallow(signal(), data)) {
      return
    }
    setSignal(() => data)
  })

  onCleanup(() => {
    unsub()
  })

  return signal
}

export function shallow<T>(objA: T, objB: T) {
  if (Object.is(objA, objB)) {
    return true
  }

  if (
    typeof objA !== 'object' ||
    objA === null ||
    typeof objB !== 'object' ||
    objB === null
  ) {
    return false
  }

  if (objA instanceof Map && objB instanceof Map) {
    if (objA.size !== objB.size) return false
    for (const [k, v] of objA) {
      if (!objB.has(k) || !Object.is(v, objB.get(k))) return false
    }
    return true
  }

  if (objA instanceof Set && objB instanceof Set) {
    if (objA.size !== objB.size) return false
    for (const v of objA) {
      if (!objB.has(v)) return false
    }
    return true
  }

  const keysA = Object.keys(objA)
  if (keysA.length !== Object.keys(objB).length) {
    return false
  }

  for (let i = 0; i < keysA.length; i++) {
    if (
      !Object.prototype.hasOwnProperty.call(objB, keysA[i] as string) ||
      !Object.is(objA[keysA[i] as keyof T], objB[keysA[i] as keyof T])
    ) {
      return false
    }
  }
  return true
}

// packages/react-store/src/index.ts
import { useMemo, useSyncExternalStore } from 'react'
import type { AnyUpdater, Store } from '@tanstack/store'

export * from '@tanstack/store'

export type NoInfer<T> = [T][T extends any ? 0 : never]

/*
This modification is totally inspired by the work carried out in version 5 of zustand

https://github.com/pmndrs/zustand/commit/6c9944b2c8d10c89e04024cd14999c85648fc310#diff-ca56e63fa839455c920562a44ebc44594f47957bbd3e9873c8a9e64104af2c41R22
*/
const useMemoSelector = <TState, TSelected = NoInfer<TState>>(
  getState: () => TState,
  selector: (state: NoInfer<TState>) => TSelected = (d) => d as any,
) =>
  useMemo(() => {
    let lastSelection: TSelected
    let lastState: TState
    return () => {
      const state = getState()

      if (!shallow(lastState, state)) {
        lastSelection = selector(state)
        lastState = state
      }

      return lastSelection
    }
  }, [getState, selector])

export function useStore<
  TState,
  TSelected = NoInfer<TState>,
  TUpdater extends AnyUpdater = AnyUpdater,
>(
  store: Store<TState, TUpdater>,
  selector: (state: NoInfer<TState>) => TSelected = (d) => d as any,
) {
  const slice = useSyncExternalStore(
    store.subscribe,
    useMemoSelector(() => store.state, selector),
    useMemoSelector(() => store.state, selector),
  )

  return slice
}

export function shallow<T>(objA: T, objB: T) {
  if (Object.is(objA, objB)) {
    return true
  }

  if (
    typeof objA !== 'object' ||
    objA === null ||
    typeof objB !== 'object' ||
    objB === null
  ) {
    return false
  }

  const keysA = Object.keys(objA)
  if (keysA.length !== Object.keys(objB).length) {
    return false
  }

  for (let i = 0; i < keysA.length; i++) {
    if (
      !Object.prototype.hasOwnProperty.call(objB, keysA[i] as string) ||
      !Object.is(objA[keysA[i] as keyof T], objB[keysA[i] as keyof T])
    ) {
      return false
    }
  }
  return true
}
