// examples/angular/simple/src/app/display.component.ts
import { injectSelector } from '@tanstack/angular-store'
import { Component, input } from '@angular/core'
import { store } from './store'

@Component({
  selector: 'app-display',
  template: `
    <!-- This will only re-render when animal changes. If an unrelated store property changes, it won't re-render -->
    <div>{{ animal() }}: {{ count() }}</div>
  `,
})
export class DisplayComponent {
  animal = input.required<'cats' | 'dogs'>()
  count = injectSelector(store, (state) => state[this.animal()])
}

// examples/svelte/simple/src/Display.svelte
<script lang="ts">
  import { useStore } from '@tanstack/svelte-store';
  import { store } from './store';

  const {animal}: { animal: 'cats' | 'dogs' } = $props()
  const count = useStore(store, (state) => state[animal]);
</script>

<!-- This will only re-render when `state[animal]` changes. If an unrelated store property changes, it won't re-render -->
<div>{ animal }: { count.current }</div>
